### ISSUE TITLE
Stuck on loading..

### ISSUE THREAD

**Issue by wenike** [lavolp3/MMM-RainCast#2]
The initial set up worked but I'm guessing something with the recent change to add in the German provider but the module is now stuck on loading rather than displaying any information.

**Comment by lavolp3** [comment]
Can you post your config please?

**Comment by wenike** [comment]
Apologies! I wanted to redact personal information out. [https://docs.google.com/document/d/1mQwKXnNwTYa8BSqJVRhqbtSkTnVCCsu-OwnFCt3QvXo/edit?usp=sharing](my current config).

**Comment by lavolp3** [comment]
Sorry the MMM-RainCast entry would have been enough. Next time I'll be more precise.

Think I fixed it.
Do a git pull and try again please

**Comment by wenike** [comment]
Fixed! Thanks!
